import { Survey } from '@/types/survey';
import { v4 as uuidv4 } from 'uuid';

export interface SurveyTemplate {
  id: string;
  name: string;
  description: string;
  icon: string;
  survey: Omit<Survey, 'id' | 'createdAt' | 'updatedAt' | 'userId'>;
}

export const surveyTemplates: SurveyTemplate[] = [
  {
    id: 'customer-feedback',
    name: 'Customer Feedback',
    description: 'Collect feedback from your customers',
    icon: '💬',
    survey: {
      title: 'Customer Feedback Survey',
      description: 'We value your opinion! Please take a few minutes to share your feedback.',
      questions: [
        {
          id: uuidv4(),
          type: 'rating',
          title: 'How satisfied are you with our service?',
          description: 'Rate your overall satisfaction',
          required: true,
          minRating: 1,
          maxRating: 5,
          order: 0,
        },
        {
          id: uuidv4(),
          type: 'single-choice',
          title: 'How did you hear about us?',
          description: 'Select one option',
          required: true,
          order: 1,
          options: [
            { id: uuidv4(), label: 'Social Media' },
            { id: uuidv4(), label: 'Friend/Family' },
            { id: uuidv4(), label: 'Advertisement' },
            { id: uuidv4(), label: 'Search Engine' },
            { id: uuidv4(), label: 'Other' },
          ],
        },
        {
          id: uuidv4(),
          type: 'textarea',
          title: 'What can we improve?',
          description: 'Share your suggestions',
          required: false,
          order: 2,
        },
        {
          id: uuidv4(),
          type: 'yes-no',
          title: 'Would you recommend us to others?',
          description: '',
          required: true,
          order: 3,
        },
      ],
    },
  },
  {
    id: 'nps',
    name: 'Net Promoter Score (NPS)',
    description: 'Measure customer loyalty with NPS',
    icon: '⭐',
    survey: {
      title: 'Net Promoter Score Survey',
      description: 'How likely are you to recommend us to a friend or colleague?',
      questions: [
        {
          id: uuidv4(),
          type: 'rating',
          title: 'On a scale of 0-10, how likely are you to recommend us?',
          description: '0 = Not at all likely, 10 = Extremely likely',
          required: true,
          minRating: 0,
          maxRating: 10,
          order: 0,
        },
        {
          id: uuidv4(),
          type: 'textarea',
          title: 'What is the primary reason for your score?',
          description: 'Please share your thoughts',
          required: false,
          order: 1,
        },
      ],
    },
  },
  {
    id: 'event-feedback',
    name: 'Event Feedback',
    description: 'Collect feedback after an event',
    icon: '🎉',
    survey: {
      title: 'Event Feedback Survey',
      description: 'Help us improve our future events by sharing your experience',
      questions: [
        {
          id: uuidv4(),
          type: 'rating',
          title: 'How would you rate the overall event?',
          description: '',
          required: true,
          minRating: 1,
          maxRating: 5,
          order: 0,
        },
        {
          id: uuidv4(),
          type: 'multiple-choice',
          title: 'What did you enjoy most? (Select all that apply)',
          description: '',
          required: false,
          order: 1,
          options: [
            { id: uuidv4(), label: 'Content/Speakers' },
            { id: uuidv4(), label: 'Networking Opportunities' },
            { id: uuidv4(), label: 'Venue/Location' },
            { id: uuidv4(), label: 'Food & Beverages' },
            { id: uuidv4(), label: 'Organization' },
          ],
        },
        {
          id: uuidv4(),
          type: 'textarea',
          title: 'Any additional comments or suggestions?',
          description: '',
          required: false,
          order: 2,
        },
        {
          id: uuidv4(),
          type: 'yes-no',
          title: 'Would you attend a similar event in the future?',
          description: '',
          required: true,
          order: 3,
        },
      ],
    },
  },
  {
    id: 'product-satisfaction',
    name: 'Product Satisfaction',
    description: 'Gauge satisfaction with a product',
    icon: '📦',
    survey: {
      title: 'Product Satisfaction Survey',
      description: 'Tell us about your experience with our product',
      questions: [
        {
          id: uuidv4(),
          type: 'rating',
          title: 'How satisfied are you with the product quality?',
          description: '',
          required: true,
          minRating: 1,
          maxRating: 5,
          order: 0,
        },
        {
          id: uuidv4(),
          type: 'rating',
          title: 'How satisfied are you with the product price?',
          description: '',
          required: true,
          minRating: 1,
          maxRating: 5,
          order: 1,
        },
        {
          id: uuidv4(),
          type: 'single-choice',
          title: 'Which feature is most valuable to you?',
          description: '',
          required: true,
          order: 2,
          options: [
            { id: uuidv4(), label: 'Quality' },
            { id: uuidv4(), label: 'Price' },
            { id: uuidv4(), label: 'Design' },
            { id: uuidv4(), label: 'Functionality' },
            { id: uuidv4(), label: 'Support' },
          ],
        },
        {
          id: uuidv4(),
          type: 'textarea',
          title: 'What would you like to see improved?',
          description: '',
          required: false,
          order: 3,
        },
      ],
    },
  },
  {
    id: 'employee-satisfaction',
    name: 'Employee Satisfaction',
    description: 'Measure employee satisfaction and engagement',
    icon: '👥',
    survey: {
      title: 'Employee Satisfaction Survey',
      description: 'Your feedback helps us create a better workplace',
      questions: [
        {
          id: uuidv4(),
          type: 'rating',
          title: 'How satisfied are you with your job?',
          description: '',
          required: true,
          minRating: 1,
          maxRating: 5,
          order: 0,
        },
        {
          id: uuidv4(),
          type: 'rating',
          title: 'How satisfied are you with work-life balance?',
          description: '',
          required: true,
          minRating: 1,
          maxRating: 5,
          order: 1,
        },
        {
          id: uuidv4(),
          type: 'rating',
          title: 'How satisfied are you with your manager?',
          description: '',
          required: true,
          minRating: 1,
          maxRating: 5,
          order: 2,
        },
        {
          id: uuidv4(),
          type: 'multiple-choice',
          title: 'What do you value most at work? (Select all that apply)',
          description: '',
          required: false,
          order: 3,
          options: [
            { id: uuidv4(), label: 'Career Growth' },
            { id: uuidv4(), label: 'Work-Life Balance' },
            { id: uuidv4(), label: 'Compensation' },
            { id: uuidv4(), label: 'Team Culture' },
            { id: uuidv4(), label: 'Job Security' },
          ],
        },
        {
          id: uuidv4(),
          type: 'textarea',
          title: 'Any additional feedback?',
          description: '',
          required: false,
          order: 4,
        },
      ],
    },
  },
];

